### ISSUE TITLE
404 Error; Needs an https:// in front of link to confirm your email

### ISSUE THREAD

**Issue by derektli97** [tamuhack-org/Ouroboros#100]
**Describe the Bug**
After opening your email to confirm your email, clicking on the link brings you to a 404 error page. 

**To Reproduce**
1. Go to your email after submission to create a new account.
2. Click on the link.
3. See error

**Expected behavior**
Should bring you to a page to confirm successful confirmation.

**Screenshots**
![image](https://user-images.githubusercontent.com/26476777/60862758-7aaf7000-a1d3-11e9-8ce2-75ff27c92c57.png)

**Comment by rstadpatri** [comment]
i still have to manually add in the https://
