### ISSUE TITLE
Add login button to return after signing up for an account

### ISSUE THREAD

**Issue by derektli97** [tamuhack-org/Ouroboros#101]
![image](https://user-images.githubusercontent.com/26476777/60863117-7f285880-a1d4-11e9-99b6-37d844ed3f9e.png)

Currently, once you finish signing up, ^^^ is the end screen. 
Just more ergonomic/efficient? to add a return button to login

**Comment by gracekfan** [comment]
- [ ] Add log in button like in password reset flow

**Comment by gracekfan** [comment]
Resolved by #133
