### ISSUE TITLE
Change all instances of Howdy Hack (two words) to HowdyHack (one word)

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/Ouroboros#103]
change in page title and everywhere else

**Comment by gracekfan** [comment]
Be more specific for both "page title" and "everywhere else"

**Comment by suvedhs** [comment]
- <title> tag
 - login page, <h1>
 - signup page, <h1>
 - application page, <h1>
 - application page, question: Have you attended Howdy Hack before?
 - application page, question: What is a cool prize you'd like to win at Howdy Hack?
