### ISSUE TITLE
Change / remove bullet point on Signup page Error messages

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/Ouroboros#104]
**Describe the Bug**
See [screenshot](https://www.dropbox.com/s/y70yhyknyy7aozf/Screenshot%202019-07-09%2021.28.29.png?dl=0)

**To Reproduce**
1. Go to /accounts/signup page
2. enter valid email and password
3. in third box, enter mismatched password

**Expected behavior**
Error message should be at top
spacing should not be jank

**Comment by sophialee0416** [comment]
@suvedhs  nice title change

I want to add in web view errors (bullets are not aligned):

<img width="393" alt="Screen Shot 2019-07-11 at 10 39 46 AM" src="https://user-images.githubusercontent.com/22566866/61072625-87e18000-a3c8-11e9-9a3f-2926eb45a2cc.png">
