### ISSUE TITLE
No scroll

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/Ouroboros#106]
**Describe the Bug**
You can't scroll. On mobile landscape view, I can't access the entire page.

**To Reproduce**
1. Open chrome on phone
2. Go to register.pango.li
4. See you can't scroll :(

**Expected behavior**
Let me scroll when Login Box is longer than screen height

**Screenshots**
[here](https://www.dropbox.com/s/95iom84i2qbxw8i/Screenshot%202018-07-29%2022.05.66.jpg?dl=0)

**Additional context**

**Comment by gracekfan** [comment]
Repeat of https://github.com/tamuhack-org/Ouroboros/pull/84#issue-293547394
