### ISSUE TITLE
Add more gender options

### ISSUE THREAD

**Issue by addisonmaupin** [tamuhack-org/Ouroboros#107]
Could we maybe add more gender options (at least an 'other') or get rid of it entirely and just ask for pronouns?

**Comment by gracekfan** [comment]
Aside from other, do you have any more suggestions?

**Comment by sophialee0416** [comment]
[Twitter has a good reference](https://2019gracehopperfellowship.splashthat.com/?fbclid=IwAR2bCrSNgmPfE2JQLA0nGntnBq7hdbnrXvx_XQrLZtDWl8NSttmBY4v6WLs)
We can ask for pronouns but I think it should be Male/Female/Non binary/Other

**Comment by gracekfan** [comment]
Resolved by #133
