### ISSUE TITLE
Error message styling inconsistent, login vs signup page

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/Ouroboros#108]
**Describe the Bug**
login page and signup page have different styling for Error messages

**To Reproduce**
1. look at error on login page
2. look at error on signup page

**Expected behavior**
They should be the same. Login page error is already styled, so make the signup page styling match.

**Comment by gracekfan** [comment]
<img width="566" alt="Screen Shot 2019-07-17 at 9 43 47 PM" src="https://user-images.githubusercontent.com/33182506/61425337-42e3af00-a8dc-11e9-9b26-490318575a7e.png">
<img width="586" alt="Screen Shot 2019-07-17 at 9 44 06 PM" src="https://user-images.githubusercontent.com/33182506/61425338-42e3af00-a8dc-11e9-809a-09820ecc3a1c.png">
<img width="574" alt="Screen Shot 2019-07-17 at 9 44 16 PM" src="https://user-images.githubusercontent.com/33182506/61425339-437c4580-a8dc-11e9-808a-9fa077db13ac.png">
<img width="584" alt="Screen Shot 2019-07-17 at 9 44 25 PM" src="https://user-images.githubusercontent.com/33182506/61425340-437c4580-a8dc-11e9-8267-82f98e7955a0.png">
