### ISSUE TITLE
Not filling out optional questions on application will produce error

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#112]
**Describe the Bug**
Warning bubble pops up for empty optional questions on application.

**To Reproduce**
1. Fill out everything except questions marked with a red asterisk
2. Submit form

**Expected behavior**
It should be ok for the applicant to submit without filling out required questions. Either remove the error message or make it required.

**Screenshots**
<img width="794" alt="Screen Shot 2019-07-11 at 11 05 35 AM" src="https://user-images.githubusercontent.com/22566866/61074219-0ab80a00-a3cc-11e9-8feb-5d57b9bd5577.png">

**Comment by SaltyQuetzals** [comment]
I think we were under the impression that this would be required, but we can make it optional with no issue

**Comment by sophialee0416** [comment]
It should be fine to make the last 3 optional, as we have made them optional in the past
