### ISSUE TITLE
Submitted application is still editable

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#113]
Should the applications be editable even after submission? If so, we should make sure that they aren't editable once the deadline passes.

I was able to edit my application after submission, and the new information gets saved when I open it again. How does this look like on the other end when I re-submit? Does the information get overridden, is a new entry formed, does it stay the same?

**Comment by SaltyQuetzals** [comment]
The originally-submitted application is overridden.

However, Hackers are unable to edit their applications outside of a
registration wave. For example, if we opened a wave on January 1, and set
it to close on January 2 at 23:59, on January 3 at 0:00, the Hacker will no
longer be able to modify the application. We can enforce the application to
be read-only after acceptance, though.

**Comment by sophialee0416** [comment]
Cool cool -- the application should be read-only after acceptance. I'll message you for the specifics.
