### ISSUE TITLE
Resume Submission Takes non-PDF's

### ISSUE THREAD

**Issue by mepoth** [tamuhack-org/Ouroboros#126]
**Describe the Bug**
I can upload a jpg for the resume submission.

**Expected behavior**
Only pdf's should be accepted, so it is easier to provide companies resumes.

**Comment by SaltyQuetzals** [comment]
We can limit the file extension to only accept PDFs, but files can be renamed to anything, so people can just create a JPG, rename it to a `.pdf`, and submit it that way. This would only be a surface-level fix.
