### ISSUE TITLE
Add functionality for re-sending emails

### ISSUE THREAD

**Issue by SaltyQuetzals** [tamuhack-org/Ouroboros#171]
**Is your feature request related to a problem? Please describe.**
Several users during the HowdyHack process encountered issues working with the registration process and couldn't find the emails for verification or resetting their password.

**Describe the solution you'd like**
We should include functionality across the application to re-send emails that are important to user flows, including:

- Verifying the user's email
- Re-sending a reset-password email

**Additional context**
Specifically for re-sending the verification email, the view needs to be accessible by non-active users (users that haven't verified their account). When attempting to log in as an unverified user, it's critical that the user instructions asking them to verify their email, rather than just telling them that their email/password are wrong.

**Comment by gracekfan** [comment]
@SaltyQuetzals is this done?
