### ISSUE TITLE
Test - Authentication System

### ISSUE THREAD

**Issue by OneWebDev** [tamuhack-org/Ouroboros#236]
**Goal: Make sure users can register, login, reset passwords, and receive confirmation codes in an orderly way.**

**Steps to complete this user path**

1. Navigate to https://register.tamuhack.com/accounts/signup/.
2. Try to submit an empty form in the signup page, or just a username, or incorrect passwords, or the email as the password. Try to find any way to cause errors in the form submission process.
3. Check a verification email has been sent to the appropriate email address and that the link works.
4. Try to break the login page the same way as the signup page.
5. Verify the password forgotten page works at https://register.tamuhack.com/accounts/password_reset/.
6. Make sure an admin can perform all the user operations in the admin panel at https://register.tamuhack.com/admin/.

**Comment by p1008217** [comment]
Didn't cause an error, but took in a random email I put in.
