### ISSUE TITLE
custauth:logout path only returns admin

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/Ouroboros#242]
When user logs out of their account, it brings them to the admin log out page. If the user clicks "login" after logging out, it goes to the admin login.

When user logs out, they should be redirected to /accounts/login

**Comment by cameron3301** [comment]
I'm having trouble replicating this bug. When I run the server, I don't see any "log out" button or any way for the user to actually log out.

**Comment by sophialee0416** [comment]
I'm still experiencing this on Safari and Chrome
