### ISSUE TITLE
Clicking submit after updating application doesn't redirect

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#249]
**Describe the Bug**
After completing an application, if a user goes back to update their application and then clicks submit, the page does not redirect back to the status page. The expected behavior of a submit operation would be a redirect.

**To Reproduce**
1. Go to submit an application
2. Submit the application
3. Click the edit application button
4. Submit application again

**Expected behavior**
Clicking submit application should redirect to status page

**Comment by sophialee0416** [comment]
I'm still experiencing this issue on Safari
