### ISSUE TITLE
Uploaded resumes are not accessible from the server

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#250]
**Describe the Bug**
When going to the admin page and clicking on an application's resume, the resume is not able to be accessed from the server

**To Reproduce**
1. Complete an application
2. Add a resume to the application
2. Go to the admin panel
3. Click on applications
4. Find the submitted application and attempt to access the resume

**Expected behavior**
The admin should be able to access the resume from the admin panel.

**Comment by SaltyQuetzals** [comment]
Fixed in the [wiki](https://github.com/tamuhack-org/Ouroboros/wiki/Differences-in-Launching#nginx-port-forwarding-setup-new). Code fixes weren't necessary.
