### ISSUE TITLE
Selecting other as an option should produce a textbox

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#251]
**Is your feature request related to a problem? Please describe.**
When clicking `Other` on an application question, a separate text box should appear, allowing a user to enter input in themselves

**Comment by SaltyQuetzals** [comment]
[This StackOverflow answer](https://stackoverflow.com/questions/24783275/django-form-with-choices-but-also-with-freetext-option) seems to be a good approach for solving this.

**Comment by SaltyQuetzals** [comment]
I don't think we're going to have the time to solve this before TH 2020, though this is definitely an important topic to address.
