### ISSUE TITLE
Test - Waves #234

### ISSUE THREAD

**Issue by soriamarissa** [tamuhack-org/Ouroboros#255]
**Describe the Bug**
When I filled in the application and submitted it an error did not occur telling me it was an invalid registration wave it just me my application has been submitted.

**To Reproduce**
1. Go to 'https://register.tamuhack.com/application/'
2. Fill out form with info 
3. Submit form
4. Redirected to 'https://register.tamuhack.com/status/' saying my application has been submitted

**Expected behavior**
An error should have appeared showing an invalid registration wave.

**Screenshots**

**Additional context**
Marissa Soria
I am using a MacBook Pro 15in, Version 10.13.6 High Sierra and Safari Version 13.0.2

**Comment by SaltyQuetzals** [comment]
@soriamarissa The current wave is open until Nov. 2. Did you modify the current wave so that submitting your application would be invalid?
