### ISSUE TITLE
Textboxs for any email input should not be case-sensitive

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#267]
**Describe the Bug**
Safari has the tendency to capitalize the first letter, which affects anything case-sensitive like the text box in the resend activation form. Ex) sophia.lee0416@gmail.com produces `No account with this email exists.`, but Sophia.lee0416@gmail.com produces `This account has already been activated.`

**To Reproduce**
1. Go to `https://register.tamuhack.com/accounts/resend_activation/`
2. Type in a verified email inside the email text box, with caps or without
3. Press `Resend Verification` Button

**Expected behavior**
I should have the same error/success messages for both email inputs

**Screenshots**
![image](https://user-images.githubusercontent.com/22566866/67627667-1c5fd900-f826-11e9-8c10-5e732c53722f.png)
![image](https://user-images.githubusercontent.com/22566866/67627669-2681d780-f826-11e9-8b00-e67f83c56130.png)

**Additional context**
Email input in log-in is also case-sensitive - I was able to create 2 accounts with the same email address, only difference is capitalized first letter

**Comment by SaltyQuetzals** [comment]
We've seen this issue before in #154. [This StackOverFlow answer](https://stackoverflow.com/a/556104) says (with an RFC for backup) that for an email address `<USERNAME>@<DOMAIN>`, `<USERNAME>` _is_ case sensitive, whereas the domain is not. Most email servers choose to have the username be case-insensitive, however that choice is left up to the mail server. I don't think we should enforce this, even if it is annoying. This could possibly cause bugs, though the case is unlikely.

Thoughts @sophialee0416?

**Comment by sophialee0416** [comment]
Interesting, learned something new. Let's leave it be then @SaltyQuetzals
