### ISSUE TITLE
Selecting All on Applications page and then unselecting a single application does not produce expected results

### ISSUE THREAD

**Issue by HumzaJaffri** [tamuhack-org/Ouroboros#270]
**Describe the Bug**
On the applications page, when all the applications on a given page are selected, there is a prompt to select all the applications. When I unselect a single application on the current page, it unselects not only the application we want but also the applications on the other pages as well.

**To Reproduce**
1. Go to the applications page
2. Select all the applications on a given page
3. You will be prompted to select all the applications, select all
4. After selecting all, unselect a single application on the current page
5. Here is where the error is, it unselects the application we wanted and also all the ones on the other pages

**Expected behavior**
Ideally, when the one application we want to unselect is clicked, it will only unselect that one and leave the rest of them on the other pages selected

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/33182937/67630203-17b11a00-f852-11e9-9b44-e7309476717e.png)
![Screenshot (1)](https://user-images.githubusercontent.com/33182937/67630204-17b11a00-f852-11e9-8ca2-c1365b57cdff.png)
![Screenshot (3)](https://user-images.githubusercontent.com/33182937/67630205-17b11a00-f852-11e9-8c45-c6dcadfe688a.png)

**Additional context**
I unselected Sophia's application and wanted all the other applications to still be selected

**Comment by SaltyQuetzals** [comment]
This is... a weird bug. I'm able to reproduce it, but none of this code is ours, I'm not sure if there's an easy fix.
