### ISSUE TITLE
Received error: "You can only submit one application to this event" when submitting fully for the first time

### ISSUE THREAD

**Issue by sophialee0416** [tamuhack-org/Ouroboros#293]
**Describe the Bug**
Attempting to submit a complete application for the first time produced the error message "You can only submit one application to this event". I had pressed submit prior for an **incomplete** application to test some bugs, which had originally prevented me from fully submitting the application. But when I completed the application and submitted it fully for the first time, I was shown that error. The error suggests that I have already submitted an application to the event, which I have not.

**To Reproduce**
1. Submit an incomplete application (the system should reject the user from submission, which is expected behavior)
2. Go back and complete the application fully
3. Submit again

**Expected behavior**
The application should have been submitted without a problem

**Screenshots**
![image](https://user-images.githubusercontent.com/22566866/67801881-210bd380-fa58-11e9-8dab-3f5c87421352.png)

**Additional context**
Bug reproduced on Chrome iOS

**Comment by SaltyQuetzals** [comment]
I think this was caused by your other bug about #295 . I couldn't reproduce it.

**Comment by sophialee0416** [comment]
Hm I'll try again.. #295 was caused on a different account

**Comment by sophialee0416** [comment]
Ok couldn't reproduce again, closing.
