### ISSUE TITLE
Hard-coded references to TAMUhack in some emails

### ISSUE THREAD

**Issue by SaltyQuetzals** [tamuhack-org/Ouroboros#337]
**Describe the Bug**
Some emails still contain hard-coded references to TAMUhack in them, and do not change when the `EVENT_NAME` setting changes. Specifically,

- [`templates/application/emails/approved.html`](https://github.com/tamuhack-org/Ouroboros/blob/85e0748467a6991a043ffb91d42ef8adb37e00d7/hiss/templates/application/emails/approved.html#L90)
- [`templates/application/emails/rejected.html`](https://github.com/tamuhack-org/Ouroboros/blob/85e0748467a6991a043ffb91d42ef8adb37e00d7/hiss/templates/application/emails/rejected.html#L42)
- [`templates/registration/password_reset.html`](https://github.com/tamuhack-org/Ouroboros/blob/85e0748467a6991a043ffb91d42ef8adb37e00d7/hiss/templates/registration/emails/password_reset.html#L52)

**Expected behavior**
These emails' contents should change when the `EVENT_NAME` setting changes.

**Additional context**
Regression tests are requested. We'd like to ensure that the event name is present in each of these emails, and to ensure that those are changing in the future.

**Comment by cameronbrill** [comment]
How would I complete regression tests?

**Comment by SaltyQuetzals** [comment]
Add tests to ensure that these conditions are being met. That way the bug can't show up again.

**Comment by cameronbrill** [comment]
@SaltyQuetzals is there an example for testing constants in email templates in the project that I can look at for guidance?

**Comment by SaltyQuetzals** [comment]
Examples:
- [Application creation email test](https://github.com/tamuhack-org/Ouroboros/blob/74ee99776b119666c85cc07977ce94c4726afb6e/hiss/application/tests/email_tests/created.py#L24)
- [Application confirmation email test](https://github.com/tamuhack-org/Ouroboros/blob/74ee99776b119666c85cc07977ce94c4726afb6e/hiss/application/tests/email_tests/confirmation.py#L29)
