### ISSUE TITLE
Broken Link for the Wiki

### ISSUE THREAD

**Issue by LeonY1** [tamuhack-org/Ouroboros#350]
**The Bug**
Broken Link for the Explanation documentation on [the wiki link](https://github.com/tamuhack-org/Ouroboros/wiki)

**To Reproduce**
1. Go to [the wiki link](https://github.com/tamuhack-org/Ouroboros/wiki)
2. Click on [explanations of the codebase](https://raw.githubusercontent.com/wiki/tamuhack-org/Ouroboros/explanations)

**Expected behavior**
Goes to this page [https://github.com/tamuhack-org/Ouroboros/wiki/Explanations-of-the-Codebase](https://github.com/tamuhack-org/Ouroboros/wiki/Explanations-of-the-Codebase)

**Comment by cameronbrill** [comment]
Thank you for bringing this to our attention. This has been fixed.
