### ISSUE TITLE
Add "Texas A&M University - San Antonio" to list of schools.

### ISSUE THREAD

**Issue by sk3p7ic** [tamuhack-org/Ouroboros#478]
When attempting to sign up for TAMUhack X, there was no option in your form for "Texas A&M University - San Antonio". As this is a member of the A&M System, I would think it best that this university be included, if possible. When attempting to browse through code to see which repository may be responsible for this list, it seemed that this may be the place. If it is elsewhere, I apologize.

In  [hiss/application/fixtures/schools.json](https://github.com/tamuhack-org/Ouroboros/blob/main/hiss/application/fixtures/schools.json), potentially add the following:
```json
  {
    "model": "application.school",
    "pk": 2075,
    "fields": {
      "name": "Texas A&M University - San Antonio"
    }
  }
```
where the "`pk`" field is updated in whichever manner you see fit.

If there is anything further that you need, please feel free to reach out to me.

\- Joshua Ibrom (sk3p7ic)

**Comment by NitroGuy10** [comment]
Thanks for the suggestion! Added :)
