### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by skandrigi** [tamuhack-org/Ouroboros#487]
**Describe the Bug**
When submitting an application form, a 500 error is returned to the user, despite the application being successfully stored in the database with the correct status.

**To Reproduce**
1. Log in to the application
2. Navigate to the application submission page
3. Fill out the application form with valid data
4. Click the submit button
5. Observe 500 error page instead of successful submission page

**Expected behavior**
After submitting the form, the user should be redirected to the success page (status page) without encountering a 500 error. The application should be stored in the database and marked as submitted.

**Screenshots**
<img width="951" alt="Screen Shot 2024-07-23 at 6 32 25 PM" src="https://github.com/user-attachments/assets/4e08a6ae-b85b-4089-8122-7f4874d29dda">

**Additional context**
- The application data is being correctly saved to the database despite the 500 error.
- The application status is correctly updated to "submitted", and submission is viewable in Applications
- The submitted application is viewable in the admin dashboard.
- Django logs do not provide additional information beyond the 500 error.
- The error occurs after successful database operations but before the response is sent back to the client.
- This issue affects the user experience but does not seem to impact data integrity.

**Comment by NitroGuy10** [comment]
Fixed. I had to enable debug logging for Gunicorn because print statements were not appearing in the Heroku logs. But the issue was just an incorrectly formatted template tag in the "application submitted" email template. Hopefully the ability to actually see print statements and exceptions in the logs will come in handy in the future! 😁
