### ISSUE TITLE
Minor problems noticed

### ISSUE THREAD

**Issue by eightants** [tamuhack-org/Ouroboros#57]
Some minor styling issues I noticed that might improve the look of the login /signup page, just some suggestions
- [x] Prevent users from entering numbers in the First Name and Last Name fields
- [x]  The background color of the login and signup page differs, intentional?
- [ ] Make 'HowdyHack 2019 Application' one line. Maybe specify if it's the login or signup page in the heading
- [ ] Make the placeholder text in the input boxes a lighter grey and not italic, smaller placeholder text
- [ ] LOGIN and REGISTER text on the buttons should be a smaller font size

Potential bugs but it might have just not been implemented yet
- [x] Forgot Password does nothing
- [x] After registering as expected like a normal hacker and confirming email, I reach a page with a progress bar and no other functionality except for logging out. Is that the end of the system?

Screenshot after confirming email, nothing else to do?
![Capture5](https://user-images.githubusercontent.com/29858539/59530170-93648880-8ea8-11e9-86fe-707051457a3d.PNG)

**Comment by gracekfan** [comment]
For the screenshot above, you need to have an open wave for something to be there. Go to /admin and you can open waves.

Although I guess we should change the screen to "Please check back when a wave opens" or something.

**Comment by gracekfan** [comment]
Re: second checkbox on list, yes, intentional.

**Comment by eightants** [comment]
That makes sense, guess I should have checked the admin console first for that lol

**Comment by SaltyQuetzals** [comment]
@eightants password reset has been handled by #60
