### ISSUE TITLE
Wave inactive when created for current date

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#63]
**Describe the Bug**
When a wave is created by an administrator, the wave does not register as being an active wave on the `/status` page.

**To Reproduce**
1. Start a new wave (this should be the only wave) in the Django admin dashboard
2. Create the wave with the start date of today
3. Go to `/status`

**Expected behavior**
The user is invited to apply during the active wave.

**Screenshots**
![Screenshot from 2019-06-19 22-19-18](https://user-images.githubusercontent.com/26334334/59816287-28b8b000-92e1-11e9-8d9d-a5510dc314fe.png)

**Comment by SaltyQuetzals** [comment]
Check `WaveManager.next_wave` and `WaveManager.next_wave`

**Comment by SaltyQuetzals** [comment]
The application functions correctly after like 30 seconds. I suspect this is a strange Django admin quirk.
