### ISSUE TITLE
Application Form Styling Issues

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/Ouroboros#86]
- [x] Left/right margins on mobile are not aligned (white card is not centered, see img)
- [x] Change styling on radio buttons so they don't look like checkboxes (see Figma)
- [x] Change styling on checkboxes
- [x] Change select styling (see Figma)
- [x] Reduce select width to 50% instead of 100% on desktop (keep 100% on mobile)
- [x] Replace default select option from --------- to -- Select Option --
- [x] Q: What race(s) do you identify with -> align check boxes into 2 or 3 columns instead of by row
- [x] Reduce height of text-area by half for questions: tell us your best programming joke and after
- [x] Replace "Notes:" with Anything else you would like us to know?
- [x] Remove "Provide any additional notes and/or comments in the text box provided"
- [x] Style choose file button to upload resume (see Figma)
- [x] Reduce bottom padding/margin between question title and the form field by 20% of what it is currently
- [ ] Add the following before the 18 or over question:
       - [ ] Add in first name field (pre-filled, but editable)
       - [ ] Add in last name field (pre-filled, but editable)
       - [ ] Add in email name field (pre-filled, but editable)
- [x] In point us to anything you'd like us to look at, change placeholder to be 
                "ex. GitHub, Devpost, personal website, LinkedIn, etc."
- [x] Reorder questions:
       - [ ] Move Are you at least 18 or older to second to last last
       - [ ] Move provide us with any additional links below choose file for resume
       - [ ] Move provide "notes:"/anything else you want us to know to very last
- [x] Remove dietary restrictions question (move to rsvp)
- [x] Remove shirt size (move to rsvp) *also change shirt size from dropdown to radio box
- [x] Update resume question to reflect what's in the Application Questions google sheets
- [x] Add Do you require any special accommodations at the event? text field

**Comment by jonathan-innis** [comment]
I think the form was changed to have the name on the application so it wouldn't be prefilled

**Comment by jonathan-innis** [comment]
Moving First Name, last name, and email pre-filled to separate issue
