### ISSUE TITLE
Add MLH CoC 

### ISSUE THREAD

**Issue by SaltyQuetzals** [tamuhack-org/Ouroboros#92]
**Is your feature request related to a problem? Please describe.**
We need to add an agreement to abide by the MLH code of conduct to the application form. A simple checkbox is fine.

**Describe the solution you'd like**
Add the field to the `Application` model

**Comment by gracekfan** [comment]
Added to https://github.com/tamuhack-org/Ouroboros/issues/96#issue-465552979
