### ISSUE TITLE
Application name fields

### ISSUE THREAD

**Issue by jonathan-innis** [tamuhack-org/Ouroboros#93]
Add the following before the 18 or over question:
- [ ] Add in first name field (pre-filled, but editable)
- [ ] Add in last name field (pre-filled, but editable)
- [ ] Add in email name field (pre-filled, but editable)

**Comment by gracekfan** [comment]
Email will not be changeable, please add first name field & last name field not pre-filled

**Comment by SaltyQuetzals** [comment]
First/last name fields are included in the `Application` form.

If the user has not created an `Application`, then the fields will be blank. If they're updating their existing `Application`, then the fields will be pre-filled. No action should be necessary. @gracekfan @jonathan-innis
