### ISSUE TITLE
Edit application questions & update RSVP form styling

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/Ouroboros#96]
APPLICATION

- [x] Make the following three fields not required:

       - Point us to anything you'd liked us to look at...
       - Do you require any special accommodations
       - Anything else you'd like us to know

- [x] Add "other" as an option for what's your major
- [x] Add "other" as an option for race
- [x] Add "other" as an option for gender
- [x] Add MLH Code of Conduct checkmark end of application
- [x] Make "Are you older than 18+" -> "Please confirm that you are 18+" and do a required checkbox instead of radio button
- [x] Add as a note to 18+ question: "Please note that freshmen under 18 must be accompanied by an adult or prove that they go to Texas A&M."

RSVP

- [ ] Change RSVP yes/no buttons to radio buttons
- [x] When yes is selected, show dietary restrictions, shirt size, etc
- [x] When no is selected, show only submit button

**Comment by sophialee0416** [comment]
For the major, is it possible to get the list by data scraping our website? Example: https://careercenter.tamu.edu/Resources/Exploring_Career_Paths/My-Major/Majors

**Comment by jonathan-innis** [comment]
> For the major, is it possible to get the list by data scraping our website? Example: https://careercenter.tamu.edu/Resources/Exploring_Career_Paths/My-Major/Majors

Done

**Comment by gracekfan** [comment]
Resolved by #133
