### ISSUE TITLE
Uneven height between /accounts/login/ page to /accounts/signup/

### ISSUE THREAD

**Issue by derektli97** [tamuhack-org/Ouroboros#98]
![image](https://user-images.githubusercontent.com/26476777/60861173-556c3300-a1ce-11e9-9b20-a2f92aa9c927.png)

![image](https://user-images.githubusercontent.com/26476777/60861183-60bf5e80-a1ce-11e9-9826-f1e626f5d8f4.png)

Jumping from login to apply; heights are different.

**Comment by gracekfan** [comment]
Closing because repeat comments, see https://github.com/tamuhack-org/Ouroboros/pull/84#pullrequestreview-257198665
