### ISSUE TITLE
Freezing and taking in bad input

### ISSUE THREAD

**Issue by derektli97** [tamuhack-org/Ouroboros#99]
**Describe the Bug**
The sign up page froze after a bad input.

**To Reproduce**
1. Go to Sign Up page
2. I used ***&&&&&@howdy.com and senpai123 for password
3. Clicked submit

**Expected behavior**
Shouldn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/26476777/60861594-d11aaf80-a1cf-11e9-80fb-1c8d733e9d57.png)

**Additional context**
On Chrome.

**Comment by gracekfan** [comment]
Cannot reproduce
